version: "3.7"

services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend
    
  client:
    container_name: react
    build:
      context: ./my-app
      dockerfile: Dockerfile
    volumes:
      - "./my-app/:/app"
      - "/app/node_modules"
    networks:
      - frontend

networks: 
  frontend:
    driver: bridge